name: Manual Release

on:
  workflow_dispatch:
    inputs:
      version_type:
        description: 'Type of version change'
        required: true
        default: 'patch'
        type: 'choice'
        options:
          - patch
          - minor
          - major
      release_branch:
        description: 'Branch to release from'
        required: true
        default: 'main'
        type: 'string'

jobs:
  publish_npm:
    name: Publish to NPM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.release_branch }}
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup PNPM
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install

      - name: Run Tests
        run: pnpm test

      - name: Setup Git User
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create Version Bump Changeset
        run: |
          VERSION_TYPE="${{ github.event.inputs.version_type }}"

          # Create a temporary changeset file
          CHANGESET_ID=$(openssl rand -hex 6)
          mkdir -p .changeset

          # Create changeset file based on version type
          cat > .changeset/$CHANGESET_ID.md << EOF
          ---
          "@mrksbnc/livekit-vue": $VERSION_TYPE
          ---

          Manual $VERSION_TYPE release triggered from GitHub Actions
          EOF

      - name: Apply Changeset
        run: pnpm changeset version

      - name: Build Package
        run: pnpm build:prod

      - name: Publish to NPM
        run: pnpm changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Push Changes
        run: |
          # If we're dealing with a prerelease, make sure we're not on a pre-branch
          if [[ "${{ github.event.inputs.version_type }}" == pre* ]]; then
            # Check if we need to exit pre mode
            if [[ "${{ github.event.inputs.version_type }}" != "prerelease" ]]; then
              pnpm changeset pre exit
            fi
          fi

          git push --follow-tags
