name: Manual NPM Publish

on:
  workflow_dispatch:
    inputs:
      version_type:
        description: 'Type of version bump (patch, minor, major)'
        required: true
        default: 'patch'
        type: 'choice'
        options:
          - patch
          - minor
          - major
      release_branch:
        description: 'Branch to release from'
        required: true
        default: 'main'
        type: 'string'

# Permissions required:
# contents: write - to push version commit & tags back to the repo.
permissions:
  contents: write

jobs:
  publish:
    name: Create Version & Publish to NPM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.release_branch }}
          fetch-depth: 0

      - name: Setup PNPM
        uses: pnpm/action-setup@v4

      - name: Setup Node.js (LTS)
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Tests
        run: pnpm test:unit

      - name: Configure Git User
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create Manual Version Bump Changeset
        id: create_changeset
        run: |
          VERSION_TYPE="${{ github.event.inputs.version_type }}"
          echo "Creating a manual $VERSION_TYPE changeset..."

          # Create a temporary unique changeset filename
          CHANGESET_ID=$(openssl rand -hex 6)
          CHANGESET_FILE=".changeset/$CHANGESET_ID.md"
          mkdir -p .changeset

          # Create changeset file content based on version type
          # Replace with your actual package name if different
          PACKAGE_NAME="@mrksbnc/livekit-vue"
          cat > $CHANGESET_FILE << EOF
          ---
          "$PACKAGE_NAME": $VERSION_TYPE
          ---

          Manual $VERSION_TYPE release triggered from GitHub Actions workflow.
          EOF
          echo "Created changeset file: $CHANGESET_FILE"
          # Output filename if needed later
          echo "changeset_filename=$CHANGESET_FILE" >> "$GITHUB_OUTPUT"

      - name: Apply Version Bump from Changeset
        id: apply_changeset
        run: pnpm changeset version

      - name: Build Package
        run: pnpm build:prod

      - name: Publish to NPM Registry
        run: pnpm changeset publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Version Commit and Tags to Remote
        run: |
          echo "Pushing commit and tags created by 'changeset version'..."
          # Push the commit and the associated tag to the specified release branch
          git push origin "${{ github.event.inputs.release_branch }}" --follow-tags
