name: Release
on:
  workflow_call:
    inputs:
      package:
        required: true
        type: boolean
      image-name:
        required: false
        type: string

jobs:
  # github release
  semver:
    runs-on: ubuntu-latest
    if: ${{inputs.package == false}}
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Set up Semver
        run: |
          npm install -g \
            semantic-release \
            @semantic-release/commit-analyzer \
            @semantic-release/github \
            @semantic-release/git \
            @semantic-release/npm \
            @semantic-release/release-notes-generator \
            @semantic-release/exec \
      - name: Release
        run: npx semantic-release
      - name: "Upload Artifact"
        uses: actions/upload-artifact@v3
        with:
          name: version
          path: version.txt

  # docker image build
  build:
    needs: semver
    runs-on: ubuntu-22.04
    if: ${{inputs.package == false }}
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: version
      - name: Log in
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
      - name: Build and Push image
        run: |
          IMAGE_NAME=${{ inputs.image-name }}
          VERSION=$(cat version.txt)
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
          docker build . --tag $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION

  # package release
  package_release:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    if: ${{inputs.package == true}}
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: "https://npm.pkg.github.com"
          scope: "@blablabs"
      - name: Set up Semver
        run: |
          npm install -g \
            semantic-release \
            @semantic-release/commit-analyzer \
            @semantic-release/github \
            @semantic-release/git \
            @semantic-release/npm \
            @semantic-release/release-notes-generator \
            @semantic-release/exec \
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build
        run: pnpm build
      - name: Release
        run: npx semantic-release
